### PR TITLE
Ruby: Re-enable Sorbet check

### LINKED ISSUE #114: Run Sorbet in CI
With https://github.com/marcoroth/herb/pull/106 we introduced RBS Inline types annotations.

It would be great if we could also use Sorbet to typecheck the codebase. Right now we are blocked because RBS aliases are not supported yet:

```
$ bundle exec srb tc

lib/herb/errors.rb:21: RBS aliases are not supported https://srb.help/3551
    21 |      #: () -> serialized_error
                       ^^^^^^^^^^^^^^^^
```

Another detail I noticed is that Sorbet doesn't support the inline type signatures for `attr_reader`, i.e this doesn't work:

```ruby
module Herb
  class Position
    attr_reader :line #: Integer
    attr_reader :column #: Integer
  end
end
```

but this does:

```ruby
module Herb
  class Position
    #: Integer
    attr_reader :line 

    #: Integer
    attr_reader :column 
  end
end
```

### PR DESCRIPTION
**Pull request by mickeytgl**
Now that Sorbet supports RBS aliases, this PR updates the Gemfile and modifies the files under `/lib` to fix any type errors raised by Sorbet

Resolves #114

### CODE REVIEW

**Comment by marcoroth** [comment]
Oh exciting! I missed that Sorbet added support for RBS type aliases!

File: templates/lib/herb/ast/nodes.rb.erb [hunk 1]
```diff
@@ -95,7 +103,7 @@ module Herb
           <%- else -%>
           output += "│   └── "
           <%- end -%>
-          output += <%= field.name %>.tree_inspect(indent).gsub(/^/, "    " * (indent + 1)).lstrip.gsub(/^/, "<%= prefix %>").delete_prefix("<%= prefix %>")
+          output += <%= field.name %>&.tree_inspect(indent)&.gsub(/^/, "    " * (indent + 1))&.lstrip&.gsub(/^/, "<%= prefix %>")&.delete_prefix("<%= prefix %>") || ""
```
Comment (mickeytgl) [inline templates/lib/herb/ast/nodes.rb.erb]: This is kind of annoying, but despite checking for `field_name` above, Sorbet still considers it could be nil, so we need to add safe navigators on every method. It does seem to work on `sig` files though. It might be one of the quirks of using Sorbet with rbs

Image

File: templates/lib/herb/ast/nodes.rb.erb [hunk 2]
```diff
@@ -1,9 +1,17 @@
 module Herb
   module AST
     <%- nodes.each do |node| -%>
+    #: type serialized_<%= node.human %> = {
+      <%- node.fields.each do |field| -%>
+      <%- is_nilable = !%w[Array[Herb::AST::Node] Array[Herb::AST::ERBWhenNode] Array[Herb::AST::ERBInNode] bool nil].include?(field.ruby_type) -%>
```
Comment (mickeytgl) [inline templates/lib/herb/ast/nodes.rb.erb:6]: As we talked about in Euruko, everything that isn't an array, or a boolean, or nil itself is nilable. @marcoroth

**Comment by mickeytgl** [comment]
Bumping this @marcoroth ⬆️ let me know if this approach makes sense or if there's something I can change

**Comment by marcoroth** [comment]
Hey @mickeytgl, is this one ready to go from your side?

**Comment by mickeytgl** [comment]
Yes, all good. sorbet should now be green. I explicitely didn't add tying on some files (like `engine.rb`) but I think it can be iterated on once there's a minimum working version

File: lib/herb/engine/debug_visitor.rb [hunk 3]
```diff
@@ -142,8 +144,6 @@ def replace_erb_nodes_recursive(node)
       end
 
       def find_top_level_elements(document_node)
-        @top_level_elements = [] #: Array[Herb::AST::HTMLElementNode]
-
```
Comment (marcoroth) [inline lib/herb/engine/debug_visitor.rb]: I think we might want to keep this line here, so that it will reset the "global" instance variable when you call it again

File: templates/lib/herb/ast/nodes.rb.erb (hunk 1 above)
Comment (marcoroth) [reply templates/lib/herb/ast/nodes.rb.erb]: I wonder if it might be worth to report this on Sorbet

File: lib/herb/engine/debug_visitor.rb (hunk 3 above)
Comment (marcoroth) [reply lib/herb/engine/debug_visitor.rb]: Actually, nvm. I think we only really call it once anyway.

**Review by marcoroth — APPROVED** [review]
@mickeytgl I was able to rebase it and resolve the last few issues, thank you!

**Comment by mickeytgl** [comment]
Nice! Sorry I ended up forgetting about this one
