### PR TITLE
Parser: Fix ERB control flow tags in attribute positions

### LINKED ISSUE #1063: Parser: Conditional boolean attribute attribute
The following
```
<details <% if @doc.registration_id.present? %>open<% end %>>
```
generates the following error:
```
<div class="herb-error-message">
   `&lt;% if %&gt;` started here but never closed with an end tag. The end tag may be in a different
</div>
```
referencing the opening `<%` tag.

The only way around the generation of this error is much longer & repetitive:
```
<% if @doc.registration_id.present? %>
  <details open>
   [...]
<% else %>
  <details open>
  [...]
<% end %>
```

### PR DESCRIPTION
**Pull request by marcoroth**
This pull request fixes the parser to correctly handle ERB control flow tags when parsing HTML attributes.

Previously, control flow tags like `<% if %>`, `<% end %>`, and `<%# comment %>` were incorrectly included as part of attribute names and values. Now, only ERB output tags (`<%=`, `<%==`) can be part of attribute names, while control flow tags properly terminate attribute name and attribute value parsing.

This enables patterns like this, where there is no space between the closing `%>` and the attribute name:

```erb
<dialog data-controller="dialog" <% if condition %>data-turbo-permanent<% end %>></dialog>
<div <% if admin? %>data-admin data-role="admin"<% end %>></div>
```

Resolves https://github.com/marcoroth/herb/issues/872
Resolves #1063

### CODE REVIEW

File: src/parser.c [hunk 1]
```diff
@@ -295,6 +295,11 @@ static AST_HTML_ATTRIBUTE_NAME_NODE_T* parser_parse_html_attribute_name(parser_T
     TOKEN_EOF
   )) {
     if (token_is(parser, TOKEN_ERB_START)) {
+      const char* tag = parser->current_token->value;
+      bool is_output_tag = (tag[2] == '=');
```
Comment (timkaechele) [inline src/parser.c]: Question: What if the tag length is less than 3?

Comment (timkaechele) [reply src/parser.c]: Nitpick: Remove the braces

Comment (marcoroth) [reply src/parser.c]: Updated in [92f4d9a](https://github.com/marcoroth/herb/pull/873/commits/92f4d9ab86382b3b7f857ceb7055f4f1d75a6fb4), thanks!
